export const PATH_NAME = {
  HOME: "/",
  RESET_PASSWORD: "/reset-password",
  VACCINE_SCHEDULE: "/vaccineSchedule",
  VACCINE: "/vaccine",
  CHILDREN: "/children",
  VACCINE_DETAIL: "/vaccine/:id",
  CHILD_PROFILE: "/child-profile",
  EDIT_CHILD: "/edit-child/:childId",
  PAYMENT_SUCCESS: "/payment-success",
  PAYMENT_FAILURE: "/payment-failure",
  MY_BOOKING: "/mybooking",
  CHUYEN_GIA: "/chuyen-gia",
  CONFIRM_EMAIL: "/confirm-email",
  INVENTORY: "/invetory",
  USER_PROFILE: "/user-profile",
  DOCTOR: "/doctor",
  DOCTOR_RECORD: "/doctor/record/:bookingId",
  BOOKING: "/booking",
  WALLET_DEPOSIT_SUCCESS: "/wallet/deposit-success",
  WALLET_DEPOSIT_FAILURE: "/wallet/deposit-failure",
  MY_WALLET: "/mywallet",
  AUTH: "/auth",
  ADMIN: "/admin",
  STAFF: "/staff",
  MANAGER: "/manager",
};
